"""initial schema

Revision ID: 1f7ead32f0fa
Revises: 
Create Date: 2026-07-05 00:08:17.232463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7ead32f0fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_service_timestamp', 'audit_log', ['service', 'timestamp'], unique=False)
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equity_portfolio_date', 'equity_snapshots', ['portfolio', 'date'], unique=True)
    op.create_table('event_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_revision', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_ticker_type_effective', 'event_records', ['ticker', 'event_type', 'effective_at'], unique=False)
    op.create_table('fundamental_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_revision', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fundamental_ticker_type_effective', 'fundamental_records', ['ticker', 'metric_type', 'effective_at'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('training_window_start', sa.Date(), nullable=False),
    sa.Column('training_window_end', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('ohlcv_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ohlcv_ticker_date', 'ohlcv_daily', ['ticker', 'date'], unique=True)
    op.create_table('portfolio_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio', sa.String(length=50), nullable=False),
    sa.Column('capital', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('portfolio', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('peak_price', sa.Float(), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('highest_price_since_entry', sa.Float(), nullable=False),
    sa.Column('entry_signals', sa.JSON(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_positions_portfolio', 'positions', ['portfolio'], unique=False)
    op.create_index('ix_positions_ticker_status', 'positions', ['ticker', 'status'], unique=False)
    op.create_table('signal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('signal_name', sa.String(length=50), nullable=False),
    sa.Column('signal_value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_ticker_name_computed', 'signal_records', ['ticker', 'signal_name', 'computed_at'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('portfolio', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('recommendation_id', sa.String(length=50), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('entry_signals', sa.JSON(), nullable=True),
    sa.Column('bar_features', sa.JSON(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trade_portfolio', 'trades', ['portfolio'], unique=False)
    op.create_index('ix_trade_recommendation', 'trades', ['recommendation_id'], unique=False)
    op.create_index('ix_trade_ticker_executed', 'trades', ['ticker', 'executed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_ticker_executed', table_name='trades')
    op.drop_index('ix_trade_recommendation', table_name='trades')
    op.drop_index('ix_trade_portfolio', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_signal_ticker_name_computed', table_name='signal_records')
    op.drop_table('signal_records')
    op.drop_index('ix_positions_ticker_status', table_name='positions')
    op.drop_index('ix_positions_portfolio', table_name='positions')
    op.drop_table('positions')
    op.drop_table('portfolio_config')
    op.drop_index('ix_ohlcv_ticker_date', table_name='ohlcv_daily')
    op.drop_table('ohlcv_daily')
    op.drop_table('model_versions')
    op.drop_index('ix_fundamental_ticker_type_effective', table_name='fundamental_records')
    op.drop_table('fundamental_records')
    op.drop_index('ix_event_ticker_type_effective', table_name='event_records')
    op.drop_table('event_records')
    op.drop_index('ix_equity_portfolio_date', table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    op.drop_index('ix_audit_service_timestamp', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
